### ISSUE TITLE
Find a way to support CraftBukkitUpToDate

### ISSUE THREAD

**Issue by Dutchy-** [TuinCraft/Interest#3]
Without losing the version number.

http://forums.bukkit.org/threads/admn-craftbukkituptodate-v2-0-keep-your-server-plugins-up-to-date-400.5026/

**Comment by silasary** [comment]
CButD recently added support for RSS Feeds instead of hard links. 
Details are in the main post (See link above)

**Comment by Dutchy-** [comment]
Thanks for notifying me! That will certainly solve my problem.
